[workspace]
members = ["wright"]
# Use the Rust 2021 resolver. 
resolver = "2"

[workspace.package]
edition = "2024"
# Use [cargo msrv](https://crates.io/crates/cargo-msrv) to make sure we get an accurate value for this. 
rust-version = "1.85.1"
